# -*- coding: utf-8 -*-
"""Projeto_Interdisciplinas_Ciências_de_Dados_Entrega_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YX8QeTHOxc5xlsfd9K3gJD1_rnVC8CTu
"""

!pip install python-bcb

import pandas as pd
import matplotlib.pyplot as plt

from bcb import sgs

#Selecionar os Dados
IPCA = sgs.get({'IPCA':433}, start='2000-01-01').reset_index()
IPCAab = sgs.get({'IPCAab':1635}, start='2000-01-01').reset_index()
IPAM = sgs.get({'IPAM':7450}, start='2000-01-01').reset_index()
Ccb = sgs.get({'Custo Cesta Basica - SP':7493}, start='2000-01-01').reset_index()

#Limpar/Uniformizar os Dados
def datas(df, nome_coluna):
  df.columns = ['Data', nome_coluna]
  df['Data'] = pd.to_datetime(df['Data'])
  return df

dfipca = datas(IPCA, 'IPCA')
dfipcaab = datas(IPCAab, 'IPCA Alimentacao e Bebidas')
dfipam = datas(IPAM, 'IPA-M')
dfccb = datas(Ccb, 'Custo Cesta Basica - SP')

#Derivar os Dados
def variacao(df, nome_coluna, variacao):
  df[variacao] = df[nome_coluna].pct_change() *100
  return df

dfipca = variacao(dfipca, 'IPCA', 'Variacao IPCA')
dfipcaab = variacao(dfipcaab, 'IPCA Alimentacao e Bebidas', 'Variacao IPCA-AB')
dfipam = variacao(dfipam, 'IPA-M', 'Variacao IPA-M')
dfccb = variacao(dfccb, 'Custo Cesta Basica - SP', 'Variacao Custo Cesta Basica - SP')

#Integrar os Dados
dfintegrar = dfipca.merge(dfipcaab, on='Data', how='inner')
dfintegrar = dfintegrar.merge(dfipam, on='Data', how='inner')
dfintegrar = dfintegrar.merge(dfccb, on='Data', how='inner')

#Formatar os Dados
dfintegrar = dfintegrar.round(2)
dfipca = dfipca.round(2)
dfipcaab = dfipcaab.round(2)
dfipam = dfipam.round(2)
dfccb = dfccb.round(2)

print(dfintegrar)