# -*- coding: utf-8 -*-
"""Projeto Interdisciplinas Ciências de Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHpoqDDJID9iEYLG8BP3-vz0R97DPTuW
"""

!pip install python-bcb

from bcb import sgs
IPCA = sgs.get({'Índice nacional de Preços ao Consumidor-Amplo':433}, start='1980-01-01')
df = IPCA.reset_index
print(df)

from bcb import sgs
IPCAab = sgs.get({'IPCA - Alimentação e bebidas':1635}, start='1991-01-01')
df = IPCAab.reset_index
print(df)

from bcb import sgs
IPAM = sgs.get({'Índice de Preços por Atacado-Mercado (IPA-M)':7450}, start='1994-01-01')
df = IPAM.reset_index
print(df)

from bcb import sgs
CBSP = sgs.get({'Custo da cesta básica - São Paulo':7493}, start='1998-01-01')
df = CBSP.reset_index
print(df)